/**
 * ChatFlow Built-in Personal Chat Themes
 * Provides 12 professionally curated themes with rich colors, accessible contrast,
 * and scoped CSS variable configurations.
 */

export const THEME_CATEGORIES = [
  'All',
  'Favorites',
  'Dark',
  'Light',
  'Colorful',
  'Minimal',
  'Nature',
  'Gaming',
];

export const BUILT_IN_THEMES = [
  {
    id: 'default',
    name: 'ChatFlow Default',
    category: 'Minimal',
    description: 'Clean, balanced adaptive ChatFlow appearance.',
    isDark: false,
    background: '#f8fafc',
    backgroundSecondary: '#ffffff',
    incomingBubble: '#ffffff',
    incomingText: '#0f172a',
    outgoingBubble: 'linear-gradient(135deg, #4f46e5 0%, #6366f1 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#ffffff',
    inputBackground: '#f1f5f9',
    inputText: '#0f172a',
    inputPlaceholder: '#94a3b8',
    primaryAccent: '#4f46e5',
    secondaryAccent: '#6366f1',
    borderColor: '#e2e8f0',
    timestampColor: '#94a3b8',
    linkColor: '#3b82f6',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'midnight',
    name: 'Midnight',
    category: 'Dark',
    description: 'Deep obsidian and navy with electric blue accents.',
    isDark: true,
    background: '#0a0f1d',
    backgroundSecondary: '#0f172a',
    incomingBubble: '#1e293b',
    incomingText: '#f8fafc',
    outgoingBubble: 'linear-gradient(135deg, #2563eb 0%, #38bdf8 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#0a0f1d',
    inputBackground: '#1e293b',
    inputText: '#f8fafc',
    inputPlaceholder: '#64748b',
    primaryAccent: '#38bdf8',
    secondaryAccent: '#60a5fa',
    borderColor: '#1e293b',
    timestampColor: '#64748b',
    linkColor: '#38bdf8',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'ocean',
    name: 'Ocean',
    category: 'Nature',
    description: 'Cool marine blues with luminous aqua and cyan tones.',
    isDark: true,
    background: '#041f2d',
    backgroundSecondary: '#083344',
    incomingBubble: '#0e4359',
    incomingText: '#ecfeff',
    outgoingBubble: 'linear-gradient(135deg, #0891b2 0%, #06b6d4 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#041f2d',
    inputBackground: '#083344',
    inputText: '#ecfeff',
    inputPlaceholder: '#155e75',
    primaryAccent: '#06b6d4',
    secondaryAccent: '#22d3ee',
    borderColor: '#0e4359',
    timestampColor: '#22d3ee',
    linkColor: '#67e8f9',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'sunset',
    name: 'Sunset',
    category: 'Colorful',
    description: 'Warm evening dusk with fiery coral and amber glow.',
    isDark: true,
    background: '#1c0e24',
    backgroundSecondary: '#2b1038',
    incomingBubble: '#3b164f',
    incomingText: '#fdf4ff',
    outgoingBubble: 'linear-gradient(135deg, #ea580c 0%, #db2777 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#1c0e24',
    inputBackground: '#2b1038',
    inputText: '#fdf4ff',
    inputPlaceholder: '#86198f',
    primaryAccent: '#f97316',
    secondaryAccent: '#ec4899',
    borderColor: '#3b164f',
    timestampColor: '#d946ef',
    linkColor: '#fb923c',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'lavender',
    name: 'Lavender',
    category: 'Colorful',
    description: 'Calming lilac and violet with gentle pastel tones.',
    isDark: false,
    background: '#faf5ff',
    backgroundSecondary: '#f3e8ff',
    incomingBubble: '#ffffff',
    incomingText: '#3b0764',
    outgoingBubble: 'linear-gradient(135deg, #7c3aed 0%, #a855f7 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#ffffff',
    inputBackground: '#f3e8ff',
    inputText: '#3b0764',
    inputPlaceholder: '#a855f7',
    primaryAccent: '#9333ea',
    secondaryAccent: '#c084fc',
    borderColor: '#e9d5ff',
    timestampColor: '#7e22ce',
    linkColor: '#7c3aed',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'rose',
    name: 'Rose',
    category: 'Colorful',
    description: 'Romantic ruby, blush, and rose quartz harmony.',
    isDark: false,
    background: '#fff1f2',
    backgroundSecondary: '#ffe4e6',
    incomingBubble: '#ffffff',
    incomingText: '#4c0519',
    outgoingBubble: 'linear-gradient(135deg, #e11d48 0%, #f43f5e 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#ffffff',
    inputBackground: '#ffe4e6',
    inputText: '#4c0519',
    inputPlaceholder: '#fb7185',
    primaryAccent: '#e11d48',
    secondaryAccent: '#f43f5e',
    borderColor: '#fecdd3',
    timestampColor: '#9f1239',
    linkColor: '#e11d48',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'forest',
    name: 'Forest',
    category: 'Nature',
    description: 'Soothing pine emerald with refreshing mint accents.',
    isDark: true,
    background: '#042114',
    backgroundSecondary: '#063320',
    incomingBubble: '#0c4a30',
    incomingText: '#ecfdf5',
    outgoingBubble: 'linear-gradient(135deg, #059669 0%, #10b981 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#042114',
    inputBackground: '#063320',
    inputText: '#ecfdf5',
    inputPlaceholder: '#047857',
    primaryAccent: '#10b981',
    secondaryAccent: '#34d399',
    borderColor: '#0c4a30',
    timestampColor: '#34d399',
    linkColor: '#6ee7b7',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'sky',
    name: 'Sky',
    category: 'Light',
    description: 'Crisp, airy cyan and cerulean morning sky aesthetic.',
    isDark: false,
    background: '#f0f9ff',
    backgroundSecondary: '#e0f2fe',
    incomingBubble: '#ffffff',
    incomingText: '#082f49',
    outgoingBubble: 'linear-gradient(135deg, #0284c7 0%, #38bdf8 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#ffffff',
    inputBackground: '#e0f2fe',
    inputText: '#082f49',
    inputPlaceholder: '#38bdf8',
    primaryAccent: '#0284c7',
    secondaryAccent: '#38bdf8',
    borderColor: '#bae6fd',
    timestampColor: '#0369a1',
    linkColor: '#0284c7',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'Minimal',
    description: 'Understated monochrome design focusing purely on words.',
    isDark: true,
    background: '#121212',
    backgroundSecondary: '#1a1a1a',
    incomingBubble: '#242424',
    incomingText: '#e5e5e5',
    outgoingBubble: '#383838',
    outgoingText: '#ffffff',
    headerBackground: '#121212',
    inputBackground: '#1a1a1a',
    inputText: '#e5e5e5',
    inputPlaceholder: '#737373',
    primaryAccent: '#a3a3a3',
    secondaryAccent: '#d4d4d4',
    borderColor: '#2e2e2e',
    timestampColor: '#737373',
    linkColor: '#d4d4d4',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'neon',
    name: 'Neon Cyber',
    category: 'Gaming',
    description: 'High-energy cyberpunk dark with vibrant neon accents.',
    isDark: true,
    background: '#07070a',
    backgroundSecondary: '#111116',
    incomingBubble: '#1b1b24',
    incomingText: '#f4f4f5',
    outgoingBubble: 'linear-gradient(135deg, #10b981 0%, #06b6d4 100%)',
    outgoingText: '#000000',
    headerBackground: '#07070a',
    inputBackground: '#111116',
    inputText: '#f4f4f5',
    inputPlaceholder: '#71717a',
    primaryAccent: '#10b981',
    secondaryAccent: '#f43f5e',
    borderColor: '#27272a',
    timestampColor: '#a1a1aa',
    linkColor: '#22d3ee',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'coffee',
    name: 'Coffee & Cream',
    category: 'Warm',
    description: 'Cozy roasted espresso, warm caramel, and creamy mocha.',
    isDark: true,
    background: '#17110e',
    backgroundSecondary: '#241a14',
    incomingBubble: '#33241b',
    incomingText: '#fef3c7',
    outgoingBubble: 'linear-gradient(135deg, #b45309 0%, #d97706 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#17110e',
    inputBackground: '#241a14',
    inputText: '#fef3c7',
    inputPlaceholder: '#78350f',
    primaryAccent: '#d97706',
    secondaryAccent: '#f59e0b',
    borderColor: '#33241b',
    timestampColor: '#b45309',
    linkColor: '#fbbf24',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
  {
    id: 'aurora',
    name: 'Aurora Borealis',
    category: 'Nature',
    description: 'Celestial night sky illuminated by emerald and teal ribbons.',
    isDark: true,
    background: '#0b1329',
    backgroundSecondary: '#111d3d',
    incomingBubble: '#19284f',
    incomingText: '#ecfeff',
    outgoingBubble: 'linear-gradient(135deg, #059669 0%, #0891b2 100%)',
    outgoingText: '#ffffff',
    headerBackground: '#0b1329',
    inputBackground: '#111d3d',
    inputText: '#ecfeff',
    inputPlaceholder: '#0e7490',
    primaryAccent: '#10b981',
    secondaryAccent: '#06b6d4',
    borderColor: '#19284f',
    timestampColor: '#2dd4bf',
    linkColor: '#34d399',
    wallpaper: '',
    wallpaperOpacity: 80,
  },
];

export const PRESET_WALLPAPERS = [
  {
    id: 'subtle_dots',
    name: 'Subtle Polka',
    url: 'data:image/svg+xml;utf8,<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="12" r="1.5" fill="%2394a3b8" opacity="0.3"/></svg>',
  },
  {
    id: 'mesh_grid',
    name: 'Geometric Grid',
    url: 'data:image/svg+xml;utf8,<svg width="40" height="40" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><path d="M0 40L40 0H20L0 20M40 40V20L20 40" fill="%236366f1" opacity="0.15"/></svg>',
  },
  {
    id: 'circuit_waves',
    name: 'Flow Waves',
    url: 'data:image/svg+xml;utf8,<svg width="60" height="30" viewBox="0 0 60 30" xmlns="http://www.w3.org/2000/svg"><path d="M0 15 Q15 0 30 15 T60 15" stroke="%2338bdf8" stroke-width="1" fill="none" opacity="0.25"/></svg>',
  },
];

export const getThemeById = (themeId) => {
  return BUILT_IN_THEMES.find((t) => t.id === themeId) || BUILT_IN_THEMES[0];
};

export const BUBBLE_STYLES = [
  { id: 'classic', name: 'Classic', desc: 'Rounded corners with subtle tails' },
  { id: 'soft', name: 'Soft', desc: 'Extra rounded pebble contours' },
  { id: 'compact', name: 'Compact', desc: 'Streamlined dense bubble padding' },
  { id: 'minimal', name: 'Minimal', desc: 'Subtle boundaries with transparent air' },
];

export const FONT_SIZES = [
  { id: 'small', name: 'Small', label: '12px' },
  { id: 'medium', name: 'Medium', label: '14px' },
  { id: 'large', name: 'Large', label: '16px' },
];

export const DENSITIES = [
  { id: 'comfortable', name: 'Comfortable', desc: 'Standard balanced spacing' },
  { id: 'compact', name: 'Compact', desc: 'Tighter row spacing for more messages' },
  { id: 'spacious', name: 'Spacious', desc: 'Airy breathing room between bubbles' },
];
